# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20161005_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_ratio_km',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
