# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_max_ratio_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_distance',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='max meeting ditance in m', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_ratio_km',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='max ratio in km', null=True),
        ),
    ]
