# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 10:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20161223_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pos',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
