# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 11:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pos',
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
