# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20161223_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_ratio_km',
        ),
        migrations.RemoveField(
            model_name='event',
            name='world',
        ),
        migrations.AddField(
            model_name='event',
            name='vision_distance',
            field=models.PositiveIntegerField(blank=True, default=1000, help_text='max vision ditance in m', null=True),
        ),
    ]
