# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20170203_1120'),
        ('event', '0009_auto_20170130_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing_event', to='event.Event')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playing_event', to='player.Player')),
            ],
        ),
    ]
