# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20170130_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meeting_distance',
            field=models.PositiveIntegerField(blank=True, default=1000, help_text='max meeting ditance in m', null=True),
        ),
    ]
