# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0012_auto_20170315_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
