# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_event_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='task_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
