# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_event_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
