# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0008_auto_20161006_1610'),
        ('game', '0002_auto_20161005_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('acquired', 'acquired'), ('solved', 'solved'), ('lost', 'lost')], default='acquired', max_length=16)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='game.Challenge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='player.Player')),
            ],
        ),
    ]
