# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20170114_2009'),
        ('clue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.Event'),
        ),
    ]
