# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0002_clue_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='game.Challenge'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='event.Event'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='player.Player'),
        ),
    ]
