# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0003_auto_20170307_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
