# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('player', '0003_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='events',
            field=models.ManyToManyField(related_name='players', to='event.Event'),
        ),
    ]
