# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('player', '0004_player_events'), ('player', '0005_auto_20161005_0837'), ('player', '0006_remove_player_events')]

    dependencies = [
        ('player', '0003_meeting'),
    ]

    operations = [
    ]
