# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='event.Event'),
        ),
    ]
