# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20161005_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='events',
        ),
    ]
