# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_meeting_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='event_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
