# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_player_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='secret',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('connected', 'connected'), ('step1', 'step1'), ('step2', 'step2'), ('waiting', 'waiting')], default='connected', max_length=16),
        ),
    ]
