# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20170203_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinterests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='player.Player'),
        ),
    ]
