# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20170203_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ia',
        ),
        migrations.AddField(
            model_name='player',
            name='ptype',
            field=models.CharField(choices=[('ai', 'AI'), ('actor', 'actor'), ('player', 'player')], default='player', max_length=16),
        ),
    ]
