# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_auto_20170314_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='extra',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
