# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_player_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='confirm_code',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
