# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_player_confirm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='associate_ai',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
