# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_player_associate_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='associate_ai',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associate_player', to='player.Player'),
        ),
    ]
