# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_auto_20170429_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ptype',
            field=models.CharField(choices=[('ai', 'AI'), ('actor', 'actor'), ('pos', 'position'), ('player', 'player')], default='player', max_length=16),
        ),
    ]
