# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0018_auto_20170501_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
