# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.TextField(blank=True, max_length=1024, null=True)),
                ('solution', models.TextField(blank=True, max_length=1024, null=True)),
                ('ctype', models.CharField(choices=[('p', 'playable player'), ('np', 'not playable player')], default='p', max_length=8)),
                ('extra', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.TextField(blank=True, max_length=1024, null=True)),
                ('solution', models.TextField(blank=True, max_length=1024, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
                ('challenges', models.ManyToManyField(related_name='games', to='game.Challenge')),
            ],
        ),
    ]
