# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ctype',
            field=models.CharField(choices=[('pj', 'player jugable'), ('pnj', 'player no jugable')], default='pj', max_length=8),
        ),
        migrations.AddField(
            model_name='challenge',
            name='extra',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
