# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170310_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='ctype',
            field=models.CharField(choices=[('p', 'playable player'), ('np', 'not playable player')], default='p', max_length=8),
        ),
    ]
