# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20170313_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='auto_assign_clue',
            field=models.BooleanField(default=True),
        ),
    ]
