# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_auto_assign_clue'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='visible_players',
            field=models.BooleanField(default=True),
        ),
    ]
