# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_visible_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='depends',
            field=models.ManyToManyField(related_name='requiedby', to='game.Challenge'),
        ),
    ]
