# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20170424_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='child_challenges',
            field=models.ManyToManyField(blank=True, related_name='parents', to='game.Challenge'),
        ),
    ]
