# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_challenge_child_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='extra',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
