# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_game_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['pk']},
        ),
    ]
